
[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
extra_scripts = pre:pre_extra_script.py
board_build.partitions = huge_app.csv

lib_deps =
    olikraus/U8g2
    knolleary/PubSubClient